name: Coverage

on:
  push:
    branches:
      - master

jobs:
  coverage:
    name: "Generate code coverage"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: output/coverage.svg
          push_badge: false

      - name: Push Badge
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: image-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
